### ISSUE TITLE
Merge static frontend

### ISSUE THREAD

**Issue by thuyvi-le** [seg491X-team36/virtual-spatial-navigation#149]
**File(s):**
- public/index.html
- src/App.js
- src/index.js
- src/components/ExperimentDetails.js
- src/components/ParticipantDetails.js
- src/components/apiFunctions.js
- src/components/LoginForm.js
- src/components/Navbar.js
- src/pages/DownloadGame.js
- src/pages/Home.js
- src/pages/ViewExperiments.js
- src/pages/ViewParticipants.js
- src/pages/ViewRejectedSignUps.js
- src/pages/ViewSignUps.js

**Comment by cadenceyeung** [comment]
Home page and Sign Ups page were pushed last week.
